//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NooliteSmartHome.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NooliteSmartHome.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application nooLite Smart Home allows to control the lighting and electric appliances by your mobile phone..
        /// </summary>
        public static string AboutPage_MainText1 {
            get {
                return ResourceManager.GetString("AboutPage_MainText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application require the hardware: nooLite control units and nooLite Ethernet gateway..
        /// </summary>
        public static string AboutPage_MainText2 {
            get {
                return ResourceManager.GetString("AboutPage_MainText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about nooLite system on the site:.
        /// </summary>
        public static string AboutPage_MainText3 {
            get {
                return ResourceManager.GetString("AboutPage_MainText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate the application.
        /// </summary>
        public static string AboutPage_RateTheApplication {
            get {
                return ResourceManager.GetString("AboutPage_RateTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOOLITE SMART HOME.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration is loading....
        /// </summary>
        public static string Common_ConfigurationIsLoading {
            get {
                return ResourceManager.GetString("Common_ConfigurationIsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration error!.
        /// </summary>
        public static string Common_LoadingConfigurationError {
            get {
                return ResourceManager.GetString("Common_LoadingConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization is completed successfully.
        /// </summary>
        public static string Common_SynchronizationIsCompletedSuccessfully {
            get {
                return ResourceManager.GetString("Common_SynchronizationIsCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string GroupItem_ApplyState {
            get {
                return ResourceManager.GetString("GroupItem_ApplyState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brightness.
        /// </summary>
        public static string GroupItem_Brightness {
            get {
                return ResourceManager.GetString("GroupItem_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        public static string GroupItem_NextColor {
            get {
                return ResourceManager.GetString("GroupItem_NextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string GroupItem_SaveState {
            get {
                return ResourceManager.GetString("GroupItem_SaveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scene.
        /// </summary>
        public static string GroupItem_Scene {
            get {
                return ResourceManager.GetString("GroupItem_Scene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smooth.
        /// </summary>
        public static string GroupItem_Start {
            get {
                return ResourceManager.GetString("GroupItem_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        public static string GroupItem_Stop {
            get {
                return ResourceManager.GetString("GroupItem_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string GroupItem_ToggleSwitcherOff {
            get {
                return ResourceManager.GetString("GroupItem_ToggleSwitcherOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string GroupItem_ToggleSwitcherOn {
            get {
                return ResourceManager.GetString("GroupItem_ToggleSwitcherOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application isn&apos;t adjusted, please edit.
        /// </summary>
        public static string MainPageEmptySettings {
            get {
                return ResourceManager.GetString("MainPageEmptySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application settings.
        /// </summary>
        public static string MainPageLinkSettings {
            get {
                return ResourceManager.GetString("MainPageLinkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to management.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR1132 Gateway address.
        /// </summary>
        public static string SettingsHostLabel {
            get {
                return ResourceManager.GetString("SettingsHostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SettingsPasswordLabel {
            get {
                return ResourceManager.GetString("SettingsPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string SettingsUserLabel {
            get {
                return ResourceManager.GetString("SettingsUserLabel", resourceCulture);
            }
        }
    }
}
